### ISSUE TITLE
Cache outdated

### ISSUE THREAD

**Issue by thejsa** [Repo3DS/shop-cache#1]
Hey @Cruel,

Just noticed the cache was outdated.

Would you like me to host a cron job on my VPS to run this script?

(contact josh.kelly27@outlook.com)

**Comment by Cruel** [comment]
No, at least not now. But thanks.

I'm going to be changing the format big time in the next cache which I'll probably commit for building tonight. I can't automatically run the script to update cache for a couple reasons: 1) format may change and the release needs to be synchronized with freeShop release and 2) the cache extraction process is slow, and if a single NES VC game was added, I don't want it to take 30+ seconds every time freeShop boots.

Instead I will be changing freeShop so that it caches missing titles itself. This will be necessary also for custom encTitleKeys dumps and not just relying on the main shared one. Also, I'm going to improve the extraction speed, I can easily cut that in half.
